apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paw-paw
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  labels:
    gitops.tier.layer: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: paw
    server: https://kubernetes.default.svc
  project: applications
  source:
    repoURL: https://github.com/Client-Engineering-Industry-Squad-1/multi-tenancy-gitops-apps.git
    path: paw/environments/base
    helm:
      parameters:
      - name: docker_registry_prefix
        value: image-registry.openshift-image-registry.svc:5000/paw
      - name: ingress.host
        value: paw-poc04.ibmpeppa.com
      - name: common.tm1Location
        value: http://tm1data.ibmpepsicopoc04.internal:5895
      - name: common.tm1ApplicationsLocation
        value: http://tm1data.ibmpepsicopoc04.internal:9510/tm1web/
      - name: common.ibmCognosServlet
        value: http://cognos-poc04.ibmpeppa.com/p2pd/servlet/dispatch
      - name: waProxy.ibmCognosGatewayUrl
        value: http://cognos-poc04.ibmpeppa.com/bi/v1/disp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true