apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rf-pipe-secrets
  namespace: dev
spec:
  encryptedData:
    CPD_PASSWORD: AgBpeR5AHS3AIk3ogTCrj0zfEvnmNUxCkBNOd3ne3IQLan6VBSpcm8B8Q+9F46eaCsb7YiQbYIOX70GMSDBiUd12GVk2IoKfX0I4XDxbardFLGNBDiOvu+8NOXlVdftMqD4SttbrUgottrupA8+Cv3YDPBSGrGKSwinWco7Q9GoxB2sxGYko5C3OqTA3L7+tVME73ilza5Pd/rbppct3HswTfjj50Ldn41cqlbaYfSWter18D1wU7xrmcPyTfuKkHblPgmVnRV0veSjl8WdlAY1zCB3v4+d3rGdefvYqswmU2zO41MhafIeWUdV2HJmxuM+hD3IpwgBr+t/iMj8jK42eX2TKr8FNXlYFMoSFvh75UVG0As7uEuSsiFjr9LcZF/0rUVsRBAUpr7ELeV4icS33b9lw9wAFTcUb2xE6FbVJTmhXQ8HVTdQyDzUoQHIhit2wmhCmqnGVcxsDgDjuDyjG/2s/XwZrbTIqY6mSr+xsnRuWSHxJ7+umVS4omC9RVrrHwx+DKhazVoBdqMb85jEBSDWZp9eotNnIVrShlQujZDYFb2VyIbb/PE8LKqzcKv/2FQjdweyt+f/32GrtQz7z3DgoZLJP8U0T4HV89EKWorT5GYN4XrhIeOH08ScqEJE5cGtjJ9O+TzkoPm3/elSLxHiP4BslWu+C5iE9+Q7Ogpr1KJXmXUsS4IbagqTXVQJutKHeP8s/5NWrfi8=
    CPD_USER: AgCRQsbaktBKdL/CS+M0QmgqZYCWNsAkJvHUVBFhv56eRhIQFt60srIywY5QD4Z6mNsuOKzlWlurWEPMW+8QwOfYUMTEM8273CV58gY2rjVPCAwQpobQB+glFWYsSzal6UP4Te9gpo7xl/sF+ECxFgGqEIbQkX9xzLXNgjCzEhC0jr+ZQRJxz7bqAloL0KZkOwAggQPa81oGsH2KLLLD7xOpL+Y77GjVUSx/Ic8nUyXZrjst1j+dVdolToSrKeJ4cSDkh8829sdS4aLT0mlv6lGSgaBJuXwZt1yB24gOFdlTUff/Ys+dGel+xLYm72HAX30weSU+gbYWrAwCsDKD4HJy/zbd1vnZecF9vvLQ4jfWi3lmcFI+THskOAYM4r9+gCyNaV+mFnoNcn3B/YgGRBx5O/OrneZmoNICchDkyXfirF0iIGKpc5eP08YtU2bpo7rI0y5NKjCyLXd6YZeleE39vYbZM0C2KKkxtgqeTtPSeQNiSqrRixdL6IlpTu/TDOwfvd6yx5YAQ6sboj0esA8yaqzw4B79G1RHe/uGauOiHSr+AKSa15FLfByhPb4w4s9rtbxELJV/IdIUW3+rmh7n1czm3oHa9rTmoyZ60UEflNBcX7HDtvBTE6bJAZ2TQoGanQmsy4eYvKinEaD2GLizkxumJHxuST520KpYpCumyUGLAWreY80e4dflODvadMbkxzH+Ww==
  template:
    metadata:
      creationTimestamp: null
      name: my-other-model-secrets-rf-pipe
      namespace: dev
    type: Opaque
