apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-other-model-secrets
  namespace: dev
spec:
  encryptedData:
    CPD_PASSWORD: AgAvBRCpDu8OT3Q+eOVcYbo7w1dB/i9Y+Q73ga+0xLPar5jnGqwJCo+wSGdRO9qzmV3ebuAbhE+jNYnPMtprnDm0fnU2hLAm8JKCaJNL2c1kdxVH1sk+CQ7NW8BD7DBItg8K6hiWTK2Uy1hJaTRPYHh6CJV+YRCQ/woBRaZSDBzKBefUBwszKokwesE34SpraeqzuLlH6oD9hmI7QyMYTRiN8ilqAYNK8EXmdI6+TCo1YvvxX0kp7cjlc60wsZXcaoqvjVckql6hBC5bmKoaN/NGSkTpijFLpoAwT6sU9XEJkyiW53JITcTbjGPI1LXKc5TXeggFxIxYAXZgKmDpabUMXu7ZgTCyv9Nzz0vsDn7dZw1BWQFIr6ueeCnWKsU6x7uLRe7gjzIpaOTassDt38q05NZT4xzVG0/N/WDhOXMSH9IWO28MuZvjLaU5G1iRitORqb9GoQzNFluYkQhT/uT1BkamAzdPVPPvdFD3GrT4xbdB+uBuiGv3BMo2bFxwChzzL9f2YqNSXh348JXzXSEZ7lfqyW3pX2pfbBgeEyfnAcUBaZboErNWnDHtBLe6R4Xk8r/QyWV7KEI+w8KH80PZFH0NyWWG5cyg0dETpN2rnmEJaLEVd5Tcw3cDWCSqbRQe6ezlhpi2ryG5JmiOOxu1frpSAo0aNtmf3OQn+paigiFSfi95o0/MTnmCdGgPqkjaEgl9Bw/dDHCF2SU=
    CPD_USER: AgCgk4rVkDLFksn3+xgxU5QEXpKbyefrxKS0ekujmY/ctWPE989Al3AmNULPRPQT5Bdw4T5GXK29GpnP/Y773OFQFgrxcVmTSMmvwvF7j0LGA7VVQF2AxGE/TYiyOK9TfxMi9fGgWoe95mb6VkmQ645s9U0zJn2j3kcGh0m+nRTPgSLWMLBZvXne7bGGUR2lY8PlkyzW8It73LLh6zFGxUB9XXX67EatlMgvdhJdj08mW6Udb+2DCV7ERtAEVEDsqxzaH2Tt9GZ0tSwzM64WxTNvBYP9naQFkkfho+y4VmszFOdGvk3FNMB2cb9nEenMtfn81z8/ztHXpR5fIGUNcRGdkbBVarjGTxl/08aQT4h53zPKv3BFrlH9fw2ZeG2kggz2FKz/GE2yP5A7mjjxOzZKj1vNIJRFW/SSeRwTbBmddXnTvWuRljAKUBiftmwJZwimQswIEdoaq/ZCo25j7b+DNdwPznOK1x5njMmq4U2bqeb5fQ8eXgV+5UGcXamwcyBsLf3+CmyLHInSapAceFhbyijwwebirhO99XamHqqzi10j6V7o6bSvYFn/X5QJqhxrXT/7OAbkXozVjKlVMUOPTvwordLMgXgHMSJj7nFqquWyZ3s/9oJ44ooHmgOFmfOblVMVQhaHRJxK2ZlpSSVrgALSOS9jfguuR4zR3QbNio/Tine/dADX2IZHhonf830OYDJrTw==
  template:
    metadata:
      creationTimestamp: null
      name: my-other-model-secrets-rf-pipe
      namespace: dev
    type: Opaque
