apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-mq-selfsigned-certificate
  annotations:
    argocd.argoproj.io/sync-wave: "260"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: mq/environments/tools/certificates/mq-selfsigned-certificate
    repoURL: https://github.com/cloud-native-toolkit-demos/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
