apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server
  labels:
    app.kubernetes.io/name: model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: model-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: model-server
    spec:
      containers:
      - name: model-server
        image: ibmpepsicomlopscr.azurecr.io/model_server:latest
        ports:
        - name: http
          containerPort: 5000