kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: document-understanding
spec:
  to:
    kind: Service
    name: document-understanding
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
