apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server
spec:
  template:
    spec:
      containers:
      - name: payload-collector
        env:
        - name: WOS_AUTH_HEADER
          valueFrom:
            secretKeyRef:
              name: payload-collector-secrets-rf-pipe
              key: WOS_AUTH_HEADER
        args: ["-c", "/fluent-bit/config/fluentbit.conf"]
        volumeMounts:
        - name: payload-collector-config
          mountPath: /fluent-bit/config
      - name: model-server
        envFrom:
          - configMapRef:
              name: rf-pipe-configmap
          - secretRef:
              name: rf-pipe-secrets
      volumes:
      - name: payload-collector-config
        configMap:
          name: payload-collector-config